export const furnitures = [
  {
    id: "177",
    name: "Comfortable sofa",
    image: require("../images/furniture1.jpg"),
    price: 950,
    liked: true,
    cat: "sofa",
    rank: ["best selling"],
    rating: 3.5,
    reviews: 1244,
  },
  {
    id: "231",
    name: "Brown sofa",
    image: require("../images/furniture2.jpg"),
    price: 750,
    liked: false,
    cat: "sofa",
    rank: ["popular"],
    rating: 3.9,
    reviews: 204,
  },
  {
    id: "316",
    name: "Dinining table",
    image: require("../images/furniture3.jpg"),
    price: 800,
    liked: true,
    cat: "table",
    rank: ["best selling", "popular"],
    rating: 4.4,
    reviews: 199,
  },
  {
    id: "413",
    name: "Brown fabric arm chair",
    image: require("../images/furniture4.jpg"),
    price: 300,
    liked: false,
    cat: "chair",
    rank: ["best selling", "popular"],
    rating: 3.9,
    reviews: 477,
  },
  {
    id: "502",
    name: "Grey couch",
    image: require("../images/furniture5.jpg"),
    price: 730,
    liked: false,
    cat: "sofa",
    rank: ["best selling", "popular"],
    rating: 4.3,
    reviews: 86,
  },
  {
    id: "665",
    name: "Steel Chair",
    image: require("../images/furniture3.jpg"),
    price: 470,
    liked: true,
    cat: "chair",
    rank: [],
    rating: 4.7,
    reviews: 244,
  },
  {
    id: "167",
    name: "Ligh Weight Sofa",
    image: require("../images/furniture1.jpg"),
    price: 709,
    liked: true,
    cat: "sofa",
    rank: ["popular"],
    rating: 4,
    reviews: 57,
  },
  {
    id: "204",
    name: "Silk Cupboard",
    image: require("../images/furniture2.jpg"),
    price: 599,
    liked: false,
    cat: "cupboard",
    rank: ["best selling", "popular"],
    rating: 4.3,
    reviews: 122,
  },
  {
    id: "323",
    name: "Books table",
    image: require("../images/furniture3.jpg"),
    price: 322,
    liked: true,
    cat: "table",
    rank: ["best selling"],
    rating: 4.4,
    reviews: 244,
  },
  {
    id: "400",
    name: "Brown fabric arm chair",
    image: require("../images/furniture4.jpg"),
    price: 155,
    liked: true,
    cat: "chair",
    rank: ["best selling", "popular"],
    rating: 4.3,
    reviews: 1098,
  },
  {
    id: "521",
    name: "White Couch",
    image: require("../images/furniture5.jpg"),
    price: 780,
    liked: false,
    cat: "bed",
    rank: ["best selling", "popular"],
    rating: 4.6,
    reviews: 1444,
  },
  {
    id: "623",
    name: "Steel Chair",
    image: require("../images/furniture3.jpg"),
    price: 700,
    liked: false,
    cat: "chair",
    rank: [],
    rating: 4.3,
    reviews: 244,
  },
  {
    id: "154",
    name: "Comfortable sofa",
    image: require("../images/furniture1.jpg"),
    price: 950,
    liked: true,
    cat: "sofa",
    rank: [],
    rating: 4.6,
    reviews: 244,
  },
  {
    id: "233",
    name: "All in One",
    image: require("../images/furniture2.jpg"),
    price: 750,
    liked: false,
    cat: "sofa",
    rank: ["best selling"],
    rating: 4,
    reviews: 247,
  },
  {
    id: "300",
    name: "Corner Plywood",
    image: require("../images/furniture3.jpg"),
    price: 200,
    liked: true,
    cat: "table",
    rank: ["popular"],
    rating: 4.3,
    reviews: 244,
  },
  {
    id: "422",
    name: "Brown fabric arm chair",
    image: require("../images/furniture4.jpg"),
    price: 300,
    liked: true,
    cat: "chair",
    rank: ["best selling", "popular"],
    rating: 4.3,
    reviews: 326,
  },
  {
    id: "522",
    name: "Grey couch",
    image: require("../images/furniture5.jpg"),
    price: 700,
    liked: false,
    cat: "sofa",
    rank: ["popular"],
    rating: 4.3,
    reviews: 455,
  },
  {
    id: "611",
    name: "Steel Chair",
    image: require("../images/furniture3.jpg"),
    price: 700,
    liked: false,
    cat: "chair",
    rank: ["best selling", "popular"],
    rating: 4.8,
    reviews: 457,
  },
];

export const furniture_cat = [
  { id: 0, name: "all", iconName: "seat-outline" },
  { id: 1, name: "chair", iconName: "seat-outline" },
  { id: 2, name: "table", iconName: "table-furniture" },
  { id: 3, name: "cupboard", iconName: "cupboard-outline" },
  { id: 4, name: "bed", iconName: "bed-queen-outline" },
];
